name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cancel_previous:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - uses: styfle/cancel-workflow-action@a40b8845c0683271d9f53dfcb887a7e181d3918b # 0.9.1
      with:
        workflow_id: ${{ github.event.workflow.id }}
        
  build_and_test_examples:
    needs: cancel_previous
    runs-on: macos-latest
    steps:
    - uses: maxim-lobanov/setup-xcode@60606e260d2fc5762a71e64e74b2174e8ea3c8bd # v1.6.0
      with:
        xcode-version: latest-stable
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: /Users/runner/Library/Developer/Xcode/DerivedData
        key: ${{ runner.os }}-spm-examples-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-spm-examples
    - name: build for ios simulator
      run: |
          cd Example/BasicExample
          xcodebuild -workspace "BasicExample.xcworkspace" -scheme "BasicExample" -sdk iphonesimulator
          